### ISSUE TITLE
투자상품의 표현항목 추가

### ISSUE THREAD

**Issue by toonitw** [devteam101/apidoc#14]
관리자와 고객단에서 각각 요구하는 표시항목이 다름.
고객단에서는 아래의 항목이 필요. 

productCode,
productName,
amount, amountFunded,
niceAvg, niceGrade,
vssAvg, vssGrade,
period, redemptionTerm,
hopeRate, giftRate,
productStatus

**Comment by 101Company** [comment]
적용 완료.
