### ISSUE TITLE
투자상품용 기업정보 필요

### ISSUE THREAD

**Issue by toonitw** [devteam101/apidoc#8]
법인 대상일 경우에 기업정보 항목이 필요. 
기존의 개인정보 항목을 함께 사용하기 어려움. 항목 성격도 다르고, 값도 인덱스가 아니라 string .

- 업종 (string)
- 사업형태 (string)
- 기업연한 (string)
- 직원수 (string)
- 연매출 (string)
- 자산정보 (string)

**Comment by 101Company** [comment]
적용 완료.
